[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GGames"
authors = [{name = "KekwEzmo", email = "KekwEzmo@proton.me"}]
dynamic = ["version", "description"]
